version: "2"

volumes:
  cnc-config:
  timelapse-config:

services:
  frontend:
    build: ./frontend
    expose:
      - "80"

  cncjs:
    build: ./3rdparty/balena-cncjs/cncjs
    # Add additional devices to this list if required.
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    cap_add:
      - SYS_RAWIO
    expose:
      - "8000"
    volumes:
      - "cnc-config:/config"

  timelapse:
    build: ./3rdparty/timelapse
    privileged: true
    volumes:
      - "timelapse-config:/capture"
    environment:
      - SERVER_PORT=4000
      - BASE_PATH=/capture
      - PUBLIC_URL=/timelapse
    expose:
      - "4000"

  # haproxy:
  #   build: ./haproxy
  #   depends_on:
  #     - timelapse
  #   ports:
  #     - "80:80"

  nginx:
    build: ./nginx
    depends_on:
      - timelapse
      - cncjs
      - frontend
    ports:
      - "80:80"