version: 2.1

volumes:
  cnc-config:
  timelapse-config:
  octoprint-data:

services:
  frontend:
    build: ./frontend
    privileged: true
    network_mode: host
    expose:
      - 8081
    ports:
      - 8081

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: localhost

  cncjs:
    build: ./cncjs
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/ttyUSB0:/dev/ttyUSB0
    cap_add:
      - SYS_RAWIO
    expose:
      - 8000
    ports:
      - 8000
    volumes:
      - cnc-config:/config

  camserver:
    build: ./3rdparty/camera
    privileged: true
    network_mode: host
    volumes:
      - timelapse-config:/capture
    environment:
      SERVER_PORT: 4000
      BASE_PATH: /capture
      PUBLIC_URL: /camserver
    expose:
      - 4000
    ports:
      - 4000

  haproxy:
    build: ./haproxy
    privileged: true
    network_mode: host
    depends_on:
      - camserver
      - cncjs
      - frontend
    expose:
      - 80
    ports:
      - 80

  octoprint:
    build: ./octoprint
    privileged: true
    network_mode: host
    volumes:
      - 'octoprint-data:/data'
    expose:
      - 5555
    ports:
      - 5555
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'