webcam:
  timelapseEnabled: false
  webcamEnabled: false
plugins:
  DisplayLayerProgress:
    showAllPrinterMessages: false
    showHeightInStatusBar: false
    showLayerInStatusBar: false
    showOnBrowserTitle: false
    showOnNavBar: false
    showOnPrinterDisplay: true
serial:                                                                                                                                 
  autoconnect: false                                                                                                                     
  baudrate: 115200                                                                                                                           
  port: /dev/ttyACM0
