FROM --platform=linux/arm/v7 octoprint/octoprint:minimal

RUN pip install --no-cache-dir \
    "https://github.com/marian42/octoprint-preheat/archive/master.zip" \
    "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/latest/download/master.zip" \
    "https://github.com/malnvenshorn/OctoPrint-FilamentManager/archive/master.zip" \
    "https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip"

# Seed the initial config.yaml
COPY ./config.yaml /data/config.yaml
COPY start.sh start.sh

CMD ["sh","start.sh"]
