FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster-build as build

WORKDIR /usr/src/app

COPY ../3rdparty/cncjs /usr/src/app/
COPY webpack.config.production.env /usr/src/app/

RUN npm install
RUN npm run prebuild-prod

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster

COPY --from=build /usr/src/app /usr/src/app

EXPOSE 8000

RUN mkdir /config

CMD /usr/src/app/bin/cncjs --controller Grbl -H 0.0.0.0 -p 8000 -c /config/cncrc
